releases:
- name: openbao
  version: 0.3.2
  url: https://github.com/cloudfoundry-community/openbao-boshrelease/releases/download/v0.3.2/openbao-0.3.2.tgz
  sha1: sha256:9c07af85d0a7fb1a5522d99c13d2b9fb0e4a8cf91c8176f37abf0ea58531df8b
